In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../test_data_export.csv")
df = df.sort_index(axis=1)
df

,I_A,I_B,I_C,I_a,I_b,I_c,No,V_A,V_B,V_C,V_a,V_b,V_c,faulted,phase_B,phase_C,phase_a,phase_b,phase_c,vuf
0,0,1,1,1,1,0,868,133025,133090,133133,13826,13829,13836,1,119.95,-120.03,-0.01,119.95,-120.02,0.000450
1,0,15,17,150,132,134,4726,131534,132366,132858,13671,13712,13801,1,119.41,-120.34,-0.01,119.46,-120.13,0.005597
2,0,1,1,0,0,0,6284,133026,133091,133132,13826,13829,13836,1,119.95,-120.03,-0.01,119.95,-120.02,0.000433
3,0,1,1,0,0,0,6034,133029,133092,133131,13826,13829,13836,1,119.96,-120.03,-0.01,119.95,-120.02,0.000419
4,0,18,15,132,164,160,5068,131874,132212,132854,13706,13689,13803,1,119.38,-120.51,-0.01,119.49,-120.32,0.005136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0,1,1,1,1,0,3362,133025,133090,133133,13826,13829,13836,1,119.95,-120.03,-0.01,119.95,-120.02,0.000446
2996,0,1,1,0,0,0,5082,133030,133093,133132,13827,13829,13836,1,119.96,-120.03,-0.01,119.95,-120.02,0.000415
2997,0,6,20,182,48,202,2240,131502,132946,132345,13668,13802,13720,1,120.03,-119.70,-0.01,120.07,-119.48,0.005709
2998,0,1,1,0,1,1,2294,133032,133089,133131,13827,13829,13836,1,119.95,-120.03,-0.01,119.95,-120.02,0.000414
2999,1,1,1,1,3,3,3897,133125,133114,133115,13835,13833,13833,0,120.00,-120.00,0.00,120.00,-120.00,0.000080

In [2]:
vuf = df['vuf']
# vuf_approx = df['vuf_approx']
faulted = df['faulted']

In [3]:
# vuf accuracy
true_values_vuf = df[((vuf >= 0.01) & (faulted == 1)) | ((vuf < 0.01) & (faulted == 0))]
print("accuracy is: ", true_values_vuf.shape[0] / df.shape[0])
true_values_vuf

accuracy is:  0.5803333333333334

,I_A,I_B,I_C,I_a,I_b,I_c,No,V_A,V_B,V_C,V_a,V_b,V_c,faulted,phase_B,phase_C,phase_a,phase_b,phase_c,vuf
6,1,2,2,14,12,18,1013,133091,133092,133065,13830,13830,13826,0,120.01,-119.99,0.01,120.03,-119.98,0.000186
7,1,1,1,1,1,1,1895,133123,133120,133122,13834,13834,13834,0,120.00,-120.00,0.00,120.00,-120.00,0.000026
8,1,1,1,0,1,1,3173,133126,133122,133122,13835,13834,13834,0,120.00,-120.00,0.00,120.00,-120.00,0.000028
9,0,303,4,27,2904,2901,2598,140536,118912,129841,14607,11744,13492,1,115.96,-130.84,-0.01,119.55,-130.79,0.125005
10,1,1,1,0,0,0,1531,133125,133124,133124,13835,13835,13835,0,120.00,-120.00,0.00,120.00,-120.00,0.000013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2990,55,57,57,917,916,943,7639,130473,130456,130339,13453,13451,13434,0,120.06,-119.97,0.59,120.68,-119.37,0.000913
2991,16,24,17,201,344,364,5659,132728,132052,132047,13778,13680,13679,0,120.17,-120.17,0.19,120.43,-120.05,0.004804
2992,1,1,1,0,0,0,3553,133125,133123,133123,13835,13835,13835,0,120.00,-120.00,0.00,120.00,-120.00,0.000018
2994,1,1,1,3,3,3,9787,133116,133114,133115,13833,13833,13833,0,120.00,-120.00,0.00,120.00,-120.00,0.000012
2999,1,1,1,1,3,3,3897,133125,133114,133115,13835,13833,13833,0,120.00,-120.00,0.00,120.00,-120.00,0.000080

# vuf_approx accuracy
true_values_vuf_approx = df[((vuf_approx >= 0.01) & (faulted == 1)) | ((vuf_approx < 0.01) & (faulted == 0))]
print("accuracy vuf_approx is: ", true_values_vuf_approx.shape[0] / df.shape[0])
true_values_vuf_approx